### ISSUE TITLE
Cannot find module 'eslint/use-at-your-own-risk'

### ISSUE THREAD

**Issue by rafa0128** [erdkse/adminlte-3-vue#44] opened 2022-10-10 11:29 UTC
[eslint] Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js » @vue/eslint-config-typescript/recommended » /Users/rafa/Documents/tech/github/adminlte-3-vue/node_modules/@vue/eslint-config-typescript/index.js': Cannot find module 'eslint/use-at-your-own-risk'

**Comment by erdkse** [comment] 2023-01-09 11:06
are you still having this issue?

**Comment by erdkse** [comment] 2023-09-19 17:38
It looks like the issue is not valid, closing the issue @rafa0128

**Closed as completed by erdkse** 2023-09-19 17:38 UTC
